---
services:
  fwextract:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: fwextract
    volumes:
      - ./config:/fwextract-configs:Z,U
      - ./firmware:/fwextract-input:Z,U
      - ./output:/fwextract-output:Z,U
